config/routes.rb
Rails.application.routes.draw do
  resources :transactions, only: [:new, :create, :index]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  def self.human_enum_name(enum_name, enum_value)
    I18n.t("activerecord.attributes.#{model_name.i18n_key}.#{enum_name.to_s.pluralize}.#{enum_value}")
  end
end

app/models/shopkeeper.rb
class Shopkeeper < ApplicationRecord
  has_many :stores
end

app/models/store.rb
class Store < ApplicationRecord
  belongs_to :shopkeeper
  has_many :transactions
end

app/models/transaction.rb
class Transaction < ApplicationRecord

  belongs_to :store

  validates :transaction_type, :occurrence, :value, :card_number, :document_number, :store_id, presence: :true
  validates :transaction_type,
            :value,
            :occurrence,
            :card_number,
            :document_number,
            :store_id,
            uniqueness: true

  enum transaction_type: {
      debit: 1,
      billet: 2,
      financing: 3,
      credit: 4,
      loan_receipt: 5,
      sell: 6,
      ted_receipt: 7,
      doc_receipt: 8,
      rent: 9
  }

  scope :search_by_store, -> (store_name = nil){
    joins(:store).where("stores.name LIKE ?", "%#{store_name}%") unless store_name.blank?
  }

  scope :search_by_cpf, -> (document_number = nil){
    where(document_number: document_number) unless document_number.blank?
  }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  skip_before_action :verify_authenticity_token
  # GET /transactions
  # GET /transactions.json
  def index
    transaction_service = TransactionsService.new(params)
    @store_names ||= transaction_service.store_names
    @transactions ||= transaction_service.list
    @transactions = @transactions.page(params[:page] || 1).per(params[:per] || 20) unless @transactions.blank?
  end

  # GET /transactions/new
  def new
    @transaction = Transaction.new
  end


  # POST /transactions
  # POST /transactions.json
  def create
    respond_to do |format|
      if TransactionsService.new(params).create_transactions
        flash[:alert] = "file sucessfully processed"
        format.html { redirect_to action: "index" }
      else
        flash[:alert] = "strange things are happening, maybe you already imported this file? please double check the file..."
        format.html { redirect_to action: "new" }
      end
    end
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestRecruitment</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  </head>
  <% flash.each do |type, msg| %>
  <div class="alert alert-info">
    <%= msg %>
  </div>
<% end %>
  <body class="main">
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/transactions/_form.html.erb
<%= form_with(model: transaction, local: true, class: 'form-page') do |form| %>
  <% if transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
        <% transaction.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="module">
    <div class="form-box">
      <img src="/header-logo.png" class="logo-blue">
      <%= form.file_field :file, class: 'btn upload-file-button' %>
      <div class="actions">
        <%= link_to 'Voltar', transactions_path, :method => :get, class: 'btn btn-default', id: 'back-button' %>
        <%= form.submit 'Importar Arquivo', class: 'btn btn-primary action-buttons', id: 'import-button'%>
      </div>
    </div>
  </div>
<% end %>

app/views/transactions/index.html.erb
<navbar class="up-side-menu">
  <img src="/header-logo.png" class="logo-blue">
</navbar>
<h1 class="transaction-h1-title" >Transações</h1>
<div class="up-side-sub-menu">
  <%= button_to 'Importar Arquivo', new_transaction_path, class: 'btn btn-primary', :method => :get %>
  <div class="filter-section">
    <%= form_tag('/transactions', method: :get, class: 'cpf-filter') do %>
      <%= search_field_tag 'document_number', 'buscar por CPF', class: 'form-control'%>
    <% end %>
    <%= form_tag('/transactions', method: :get, class: 'store-filter', id: 'store_filter') do %>
      <%= select_tag 'store_name',
                     options_for_select(@store_names),
                     :onchange => "this.form.submit()",
                     prompt: params[:store_name],
                     class: 'btn'
      %>
    <% end %>
    <%= button_to 'Limpar Filtro', transactions_path, class: 'btn clean-filter-button', :method => :get %>
  </div>
</div>

<table class="table table-sm" id="transactions-table">
  <thead>
  <tr>
    <th class="header-table-title" scope="col">Transaction type</th>
    <th class="header-table-title" scope="col">Occurrence</th>
    <th class="header-table-title" scope="col">Card number</th>
    <th class="header-table-title" scope="col">Document number</th>
    <th class="header-table-title" scope="col">Value</th>
  </tr>
  </thead>

  <tbody>
  <% @transactions.each do |transaction| %>
    <tr class="bg-info" scope="row">
      <td class="transaction-row"><%= Transaction.human_enum_name('transaction_types', transaction.transaction_type.to_s) %></td>
      <td class="transaction-row"><%= transaction.occurrence.strftime("%Y/%m/%d %H:%M:%S") %></td>
      <td class="transaction-row"><%= transaction.card_number %></td>
      <td class="transaction-row"><%= transaction.document_number %></td>
      <td class="transaction-row"><%= transaction.value %></td>
    </tr>
  <% end %>
  </tbody>
</table>
<table class="table table-sm">
  <thead>
  <tr>
    <th class="total-value-row" scope="col">Valor Total:</th>
    <th class="total-value-row total-value" scope="col"> <%= @transactions.sum(:value) %> </th>
    <th class="total-value-row" scope="col">Quantidade Total:</th>
    <th class="total-value-row total-value" scope="col"> <%= @transactions.count %> </th>
  </tr>
  </thead>
</table>

<%#= link_to_previous_page @transactions, 'anterior' %>

<%#= link_to_next_page @transactions, 'proxima' %>

app/views/transactions/new.html.erb
  <%= render 'form', transaction: @transaction %>